### ISSUE TITLE
您好，中秋节快乐！

### ISSUE THREAD

**Issue by youngmind6** [hello-www-1/zhi-xiao-yuan-app#1]
感谢您的软件，我在下载安装后打开报错，打开后提示弹窗标题为：A JavaScript error occurred in the main process 
内容是UNcaught exception：Typeerror：cannot read propertu"split"of undefined at.....
请问您 这个该怎么解决呢？再次感谢您的软件。哈哈哈

**Comment by qwq4545** [comment]
这个软件更新了3.02，但是这个免费洗澡脚本好像只能支持3.01

**Comment by qwq4545** [comment]
作者大大可以更新一个智校园3.02免费洗澡

**Comment by youngmind6** [comment]
> 这个软件更新了3.02，但是这个免费洗澡脚本好像只能支持3.01

请问你说的是什么意思呀，我安卓APP更新了智校园就无法使用了，然后我发现作者14天前更新的，我下载作者最新软件发现我提出的那样报错，我下的windows版本，你呢？有错误吗？和我一样无法使用嘛？

**Comment by youngmind6** [comment]
> 作者大大可以更新一个智校园3.02免费洗澡

哦哦，我的app也是3.02版本，不更新没网络，我不晓得作者是公司人员还是我校学长，根本不敢多问

**Comment by qwq4545** [comment]
软件更新3.02之后，前段时间3.01还是可以正常使用的，但是现在3.01已经用不了了

**Comment by qwq4545** [comment]
这个免费洗澡APP不支持3.02

**Comment by qwq4545** [comment]
软件更新3.02之后，前段时间3.01还是可以正常使用的，但是现在3.02已经用不了了

**Comment by youngmind6** [comment]
> 软件更新3.02之后，前段时间3.01还是可以正常使用的，但是现在3.02已经用不了了

是的，哈哈，只能期待更新，开发者（学长吧）大好人

**Comment by zerotwo112** [comment]
@hello-www-1 感谢您的软件 等待更新

**Comment by hello-www-1** [comment]
已更新

**Comment by qwq4545** [comment]
@hello-www-1 太感谢了，已经用上新的了，再次感谢作者大大
